### ISSUE TITLE
Add Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-house-lannister#14]
## User Story
As a user, I should be able to add messages by clicking enter.

## AC
**Given** A user navigates to your page
**Then** they type in the input field
**And** when they hit enter a new message should be created
**And** the message should show up in the new chat window

## Dev Notes
* Create a function called `addMessage`
* `addMessage` will retrieve the value of `message-input` from the nav-bar and create a new object inside array `messageArray` with the key value pairs of `username`, `messageText`, `id`.
* `addMessage` will call `messageDomStringBuilder` to re-write the div `message-container` with the updated array

* `addMessage` will need to give each new object an `id`. 
* Create a variable called `idCounter` and set the value to 6
* `newObject.id = idCounter`
* increment `idCounter` by 1 after the new message object is added to the `messageArray`
* the `delete` button id for each message will = `object.id`
* call `getTimeStamp` and set `newObject.timeStamp = getTimeStamp`

**Comment by wchipchase** [comment]
![image](https://user-images.githubusercontent.com/15699736/56853470-2abc4f00-68ee-11e9-8a7c-d6c062b7ba4b.png)
