### ISSUE TITLE
Clear Messages

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-house-lannister#15]
## User Story
As a user, when I have messages, I should be able to clear them out with a single button.

As a user, when I DON'T have messages, I should not be able to click the clear button

## AC
**Given** A user navigates to your page
**Then** they see a bunch of messages
**And** they click the clear button
**And** the chat history should get cleared out

**Given** A user navigates to your page
**And** they see no messages
**Then** the clear button should be disabled.

## Dev Notes
* create a function called `clearMessages`

* if `messageArray.length !== 0`, see below
* `addEventListener('click', clearMessages)`
* clearMessages will set `messageArray` to an empty array `[]`
* call messageDomStringBuilder to re-write `message-container` 

* if `messageArray.length === 0`, see below
* `getElementById('clearButton').display = none;`

**Comment by wchipchase** [comment]
![image](https://user-images.githubusercontent.com/15699736/56853476-3871d480-68ee-11e9-8f14-ca676f5aa2f6.png)
