### ISSUE TITLE
Delete Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-house-lannister#17]
## User Story
As a user I should be able to delete messages.

If you are doing multiple users you should only be able to delete **your** messages

## AC
**Given** A message on your page
**Then** there should be a delete button for each message
**And** when the button is pushed the message should no longer exist

## Dev Notes
* create a function called `deleteMessage`
* each delete button will have an id that equals the id of the message object
* use filter to check and see if `messageArray` contains an object that has an id that matches the id of the delete button
* if `messageArray` contains an object with an id that equals the button id, splice that object out of the array, and re-write the dom with the updated array. 
* use for loop to check for id, set `messageIndex = i`, splice out `messageIndex` outside of the for loop

**Comment by wchipchase** [comment]
![image](https://user-images.githubusercontent.com/15699736/56853478-41fb3c80-68ee-11e9-8039-ed6d9bdbb231.png)
