### ISSUE TITLE
Display Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-house-lannister#18]
## User Story
As a user, when the page loads, I should see messages.

## AC
**Given** A user navigates to your page
**Then** they should see the 5 messages from `db/messages.json`
**And** when they add messages it should add them to the list

## Dev Notes
* No need to wait for event listener to work - use axios call to get the messages inside `messages.json`
* add an html div with an id `message-container` that will be used as the location `messageDomStringBuilder` prints to
* create a function called `messageDomStringBuilder` that takes the imported array from `messagesData.js` and loops through it to print it to the dom
* the function will also add a `delete` button with an id corresponding with the `id` property of the printed message object
* `messageDomStringBuilder` will create a section on the bootstrap card for the timeStamp, setting the timestamp on that specific card to the `timeStamp` value in the object. 
- add helper folder with a data folder
- add messagesData.js file to the data folder
- import axios into the messageData.js file
- create a `getMessagesData` function with a get request that pulls the json data from messages.json
- create an empty array called messagesArray in messages.js

**Comment by wchipchase** [comment]
![image](https://user-images.githubusercontent.com/15699736/56853469-242dd780-68ee-11e9-9190-7dc367ee39ee.png)
