### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-house-lannister#3]
## User Story
As a user, with sensitive eyes, I should be able to chat using a dark theme.

## AC
**Given** A user navigates to your page
**Then** they should see a checkbox below the input field called "Dark Theme"
**And** they should be able to click this checkbox
**And** when the checkbox is selected the page should show a dark theme with lightly colored text

## Dev Notes
- create a 'darkTheme` function
- create a variable called textColor and set it equal to document.getElementById('message-container);
- then create a conditional
- if (textColor.checked === true)
backgroundcolor = black
color = white
- call this function in the 'messageDomStringBuilder

**Comment by wchipchase** [comment]
![image](https://user-images.githubusercontent.com/15699736/56853494-648d5580-68ee-11e9-9027-7fde5a5e3e24.png)
