### ISSUE TITLE
Message Limit

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-house-lannister#8]
## User Story
As a user, I have a short attention span, and only want to see the last 20 messages.

## AC
**Given** A user navigates to your page
**Then** they should only see the last 20 messages

## Dev Notes
* in `addMessage`, before the input value is  added to the array, 
`if (messageArray.length >= 20) {
   messageArray.shift()
}`

**Comment by wchipchase** [comment]
![image](https://user-images.githubusercontent.com/15699736/56853486-4f182b80-68ee-11e9-96ad-234e5da5098e.png)
