### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-house-lannister#9]
## User Story
As a user, using all the chatting sites, I always see clean looking timestamps.

**Dirty Timestamp:**  2014-09-08T08:02:17-05:00
**Clean Timestamp:**  September 8, 2014 8:02 PM

## AC
**Given** A user navigates to your page
**Then** they see all the messages
**And**  the messages should have nice looking timestamps

## Dev Notes
* Real JS developers hate dates - they use a magical library called [MomentJS](https://momentjs.com/)
```js
npm install moment --save
```
* create a function called `getTimeStamp`
* create variable called `timeStamp`
* `timeStamp = moment().format("MMMM Do YYYY, h:mm:ss a");`
* return `timeStamp`

**Comment by mtgill** [comment]
https://momentjs.com/docs/#/displaying/

`moment().format("dddd, MMMM Do YYYY, h:mm:ss a"); // "Sunday, February 14th 2010, 3:25:50 pm"`

**Comment by wchipchase** [comment]
![image](https://user-images.githubusercontent.com/15699736/56853467-1a0bd900-68ee-11e9-97b3-2e7c139a43c6.png)

**Comment by wchipchase** [comment]
👍
